# lines with the # symbol will be ignored
# general configs
shell=bash
auto_exec=false
keep_arg_on_logs=true
save_logs_to_file=false
#prompt configs
custom_prompt=false
custom_prompt_string=$
show_path=false
user_name=false
bash_like_prompt=true
full_name_OS=false
# configure your shell
debug_mode=false
show_mem=false
# os config
unknown_os_allowed=false
# in case you cant run it on your machine, open a forum
win_always=false
linux_always=false
linux_distro=mint
distro_not_os=false
# false: your OS/custom prompt will be printed
# true: your Distro will be printed instead of your OS
# plugins
apply_plugins=false
# custom configs