# lines with the # symbol will be ignored
# general configs
shell=bash
auto_exec=false
custom_prompt=false
custom_prompt_string=$ 
# configure your shell
debug_mode=false
show_mem=false
# os config
unknown_os_allowed=false
# in case you cant run it on your machine, open a forum
win_always=false
linux_always=false
linux_distro=mint
distro_not_os=false
# false: your OS/custom prompt will be printed
# true: your Distro will be printed instead of your OS
# printing config
full_name_OS=false
# for example: LNX -> Linux, WIN -> Windows
# plugins
apply_plugins=false
# custom configs
